### ISSUE TITLE
Long fades don't transition smoothly.

### ISSUE THREAD

**Issue by Syonyk** [Syonyk/MIDI_to_DMX#1]
If a fade is in progress (say a 10 second fade from 80% to 70%) and another fade is requested (to 60%), the fade restarts from the beginning (so jumps back up to 80% and fades to 60%).  This is a known issue in the code, and wasn't a problem until Easter.

Desired new behavior is that if a fade is requested while a fade is in progress, use the current state as the new starting point - so if transitioning from 80% to 70%, and a 5 seconds in, a 10 second 60% fade is requested, start a 10 second fade from 75% to 60%.  This should keep things smooth and prevent fades from running longer than desired (as stacking them would cause), while also keeping memory use low (there will never be a need to queue fades).

**Comment by greigs** [comment]
Thanks for this code, I found it useful for my project. I also noticed this issue. Although it is minor, I was wondering if you'd had any time to look at it?
Thanks!

**Comment by Syonyk** [comment]
I haven't yet, but was going to fix it in the next week or two prior to this year's Good Friday service.

**Comment by Syonyk** [comment]
Please take a look at the recent push (from Mar 23).  It should fix the fade behavior for fade-during-fade.

Be aware that it adds the time to the fade - if you want to reset it to simply use the new fade time, that's an easy tweak to the code.  Closing the issue as fixed, unless other problems are found.
